options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'    
    args: ['build', '-t', 'us-central1-docker.pkg.dev/serverless-440117/qdp-frontend/frontend:latest', '.']
  
  # Step 2: Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/serverless-440117/qdp-frontend/frontend:latest']
  
  # Step 3: Deploy the image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'frontend-service'
      - '--image'
      - 'us-central1-docker.pkg.dev/serverless-440117/qdp-frontend/frontend:latest'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'

  # Step 4: Grant public access to the Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'services'
      - 'add-iam-policy-binding'
      - 'frontend-service'
      - '--region'
      - 'us-central1'
      - '--member=allUsers'
      - '--role=roles/run.invoker'

images:
  - 'us-central1-docker.pkg.dev/serverless-440117/qdp-frontend/frontend:latest'